---
name: bank-network-ICICI
version: 1.0.0
client:
  organization: ICICI
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  ICICI:
    mspid: ICICIMSP
    peers:
    - peer0.ICICI.bank.com
    - peer1.ICICI.bank.com
    certificateAuthorities:
    - ca.ICICI.bank.com
peers:
  peer0.ICICI.bank.com:
    url: grpcs://localhost:9051
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICUDCCAfagAwIBAgIRAMNUfjwr5qIk9MG1Me4BWmkwCgYIKoZIzj0EAwIwcjEL
        MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
        cmFuY2lzY28xFzAVBgNVBAoTDklDSUNJLmJhbmsuY29tMR0wGwYDVQQDExR0bHNj
        YS5JQ0lDSS5iYW5rLmNvbTAeFw0yMDA3MjAxNjEyMDBaFw0zMDA3MTgxNjEyMDBa
        MHIxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1T
        YW4gRnJhbmNpc2NvMRcwFQYDVQQKEw5JQ0lDSS5iYW5rLmNvbTEdMBsGA1UEAxMU
        dGxzY2EuSUNJQ0kuYmFuay5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQ3
        vjXF+y+9hxbvLu7MGWvPLIjDCNOgff1P+xUDpFaDyx5U+KngPPGNkA4dUssTczit
        fP234Q4JT5zwQo30J2W8o20wazAOBgNVHQ8BAf8EBAMCAaYwHQYDVR0lBBYwFAYI
        KwYBBQUHAwIGCCsGAQUFBwMBMA8GA1UdEwEB/wQFMAMBAf8wKQYDVR0OBCIEICKh
        26Uwowa2kY8EHHAbu5bSll3BJF9i6KIrS3+X29mSMAoGCCqGSM49BAMCA0gAMEUC
        IQDYr2v3KwPjAtLW4KPlRQOhJRuULh18+LckvxPSmKAJswIgcfD3FEbP5SQWZCfM
        PmEL7t81wpOin4cR6V1oNLrGwaQ=
        -----END CERTIFICATE-----
        
    grpcOptions:
      ssl-target-name-override: peer0.ICICI.bank.com
      hostnameOverride: peer0.ICICI.bank.com
  peer1.ICICI.bank.com:
    url: grpcs://localhost:10051
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICUDCCAfagAwIBAgIRAMNUfjwr5qIk9MG1Me4BWmkwCgYIKoZIzj0EAwIwcjEL
        MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
        cmFuY2lzY28xFzAVBgNVBAoTDklDSUNJLmJhbmsuY29tMR0wGwYDVQQDExR0bHNj
        YS5JQ0lDSS5iYW5rLmNvbTAeFw0yMDA3MjAxNjEyMDBaFw0zMDA3MTgxNjEyMDBa
        MHIxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1T
        YW4gRnJhbmNpc2NvMRcwFQYDVQQKEw5JQ0lDSS5iYW5rLmNvbTEdMBsGA1UEAxMU
        dGxzY2EuSUNJQ0kuYmFuay5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQ3
        vjXF+y+9hxbvLu7MGWvPLIjDCNOgff1P+xUDpFaDyx5U+KngPPGNkA4dUssTczit
        fP234Q4JT5zwQo30J2W8o20wazAOBgNVHQ8BAf8EBAMCAaYwHQYDVR0lBBYwFAYI
        KwYBBQUHAwIGCCsGAQUFBwMBMA8GA1UdEwEB/wQFMAMBAf8wKQYDVR0OBCIEICKh
        26Uwowa2kY8EHHAbu5bSll3BJF9i6KIrS3+X29mSMAoGCCqGSM49BAMCA0gAMEUC
        IQDYr2v3KwPjAtLW4KPlRQOhJRuULh18+LckvxPSmKAJswIgcfD3FEbP5SQWZCfM
        PmEL7t81wpOin4cR6V1oNLrGwaQ=
        -----END CERTIFICATE-----
        
    grpcOptions:
      ssl-target-name-override: peer1.ICICI.bank.com
      hostnameOverride: peer1.ICICI.bank.com
certificateAuthorities:
  ca.ICICI.bank.com:
    url: https://localhost:8054
    caName: ICICI-CA
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICSTCCAe+gAwIBAgIQU3YNqSC/ZM0C26H7EzArEzAKBggqhkjOPQQDAjBvMQsw
        CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
        YW5jaXNjbzEXMBUGA1UEChMOSUNJQ0kuYmFuay5jb20xGjAYBgNVBAMTEWNhLklD
        SUNJLmJhbmsuY29tMB4XDTIwMDcyMDE2MTIwMFoXDTMwMDcxODE2MTIwMFowbzEL
        MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
        cmFuY2lzY28xFzAVBgNVBAoTDklDSUNJLmJhbmsuY29tMRowGAYDVQQDExFjYS5J
        Q0lDSS5iYW5rLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABJ6TDmD8cL+V
        07gnyFkEKN/JdKK+8rYU8wNZJRohBvFMvanDd+zFwDo4u93s7GcvX3o0GoTHcjNi
        YlxZRkIVoi2jbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNVHSUEFjAUBggrBgEFBQcD
        AgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNVHQ4EIgQg5YiuHYplr/+G
        h6lHFCYCu0mNicIQoorPy48JiZBarr8wCgYIKoZIzj0EAwIDSAAwRQIgDadcefPE
        ZXXrC0zUja6hxF1mDsOnyvuxM0Jm/8tMLHICIQCqsetPi1VFCJ86Tmf+SSCol3U/
        Y4W/pvZOrJB/VX2QrA==
        -----END CERTIFICATE-----
        
    httpOptions:
      verify: false
