version: '2'

networks:
  bank:

services:

  HDFC-CA:
    image: hyperledger/fabric-ca:1.4.8
    environment:
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=artifacts_bank
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=HDFC-CA
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./fabric-ca/HDFC-RCA:/etc/hyperledger/fabric-ca-server
    container_name: HDFC-CA
    networks:
      - bank

  ICICI-CA:
    image: hyperledger/fabric-ca:1.4.8
    environment:
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=artifacts_bank
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ICICI-CA
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=8054
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./fabric-ca/ICICI-RCA:/etc/hyperledger/fabric-ca-server
    container_name: ICICI-CA
    networks:
      - bank

  RBI-CA:
    image: hyperledger/fabric-ca:1.4.8
    environment:
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=artifacts_bank
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=RBI-CA
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=9054
    ports:
      - "9054:9054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./fabric-ca/RBI-RCA:/etc/hyperledger/fabric-ca-server
    container_name: RBI-CA
    networks:
      - bank
